import './Fact.css';
import { useState, useEffect } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faRotateRight,
  faDollar,
  faCode,
} from '@fortawesome/free-solid-svg-icons';

function Fact() {
  const [fact, setFact] = useState<string>('');
  const [factNum, setFactNum] = useState<number>(0);

  useEffect(() => {
    setFact(
      'The war between white and brown chickens can be dated back to the great cock fight of 1432.'
    );
    setFactNum(100);
  }, []);

  return (
    <div className="Fact">
      <div className="heading">Fact #{factNum}</div>

      <div className="animalFact text-container">
        <p>{fact}</p>
        <button type="button" className="btn" onClick={__fetchFact}>
          Get New Fact <FontAwesomeIcon icon={faRotateRight} />
        </button>
      </div>
      <div className="heading">External Links</div>
      <div className="linkArea text-container">
        <p>
          Totally True Animal Facts is an open source project on Github. The
          project has over 1000 "facts" generated by ChatGPT. View the
          repository if you'd like to see the full list or view the source code.
        </p>
        <a
          type="button"
          className="btn"
          href="https://github.com/callmekass/totally-true-animal-facts"
          target="_blank"
        >
          View Repository <FontAwesomeIcon icon={faCode} />
        </a>
        <p>
          Okay we had a good laugh, now its time to get serious. On average, 150
          species go extinct every day. Thats over 55,000 species per year. Do
          your part to save these creatures and donate today.
        </p>
        <a
          type="button"
          className="btn"
          href="https://wildnet.org/"
          target="_blank"
        >
          Donate Now <FontAwesomeIcon icon={faDollar} />
        </a>
      </div>
    </div>
  );

  function __fetchFact() {
    setFact('Yaaaayyyyyy');
    setFactNum(factNum + 1);
  }
}

export default Fact;
